title: Rete regionale Archivi UDI Emilia-Romagna
description: >
  La Rete Regionale Archivi UDI Emilia-Romagna è una associazione di promozione sociale, nata nel 1989 come forma di coordinamento tra gli archivi Udi di Bologna, Ferrara, Forlì, Imola, Modena, Ravenna e Reggio Emilia. Fa parte della rete anche il Centro Documentazione Donna di Modena, dove sono depositati gli archivi dell’UDI di Modena.
logo: logo-rete-archivi-udi.jpg

exclude:
  - site
  - __*
  - Gemfile
  - Gemfile.lock

sass:
    sass_dir: _sass

collections:
  generale:
    output: true
  archivi:
    output: true
  progetti:
    output: true
  appuntamenti:
    output: true

defaults:
  - values:
      layout: default
